FROM openjdk:11-jdk-slim
ARG TOKEN_ARG
ARG DB_PASS_ARG
ARG MYSQL_HOST_ARG
ENV TOKEN=$TOKEN_ARG
ENV DB_PASS=$DB_PASS_ARG
ENV MYSQL_HOST=$MYSQL_HOST_ARG

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]